sudo: false
dist: trusty
language: node_js
node_js:
- '6'
- '7'
- '8'

cache:
  yarn: true
  directories:
     - ./node_modules

#deploy:
#  provider: npm
#  email: npm-account@email.address
#  api_key:
#    secure: "...encrypted key..."
#  on:
#    tags: true
